### ISSUE TITLE
Femme géomaticienne : nouvelle page !

### ISSUE THREAD

**Issue by KazeNoOni** [Guts/temp-test#1]
### Avez-vous un lien avec le contenu proposé ?

- [X] Oui
- [ ] Non

### Votre nom

DMONTAGNE

### Votre adresse email

montagnedelphine@gmail.com

### Licence

- [X] J'accepte

### Section / catégorie

Divers

### Mots-clés

Wikipédia, QGIS, Panda

### Titre de la news

Anita Graser sur Wikipédia

### Icône de la news

https://cdn.geotribu.fr/img/internal/icons-rdp-news/social.png

### Contenu de la news

```markdown
Très connue dans la communauté QGIS, Anita Graser a proposé plusieurs plugins, livres (dont certains en libre-accès) et développé la bibliothèque MovingPandas. Son parcours, ses réalisations détaillées et ses (nombreuses) récompenses sont à découvrir sur sa page Wikipédia en français :
https://fr.wikipedia.org/wiki/Anita_Graser
Vous parlez bien anglais/allemand et vous connaissez un peu Wikipédia ? La biographie n'attend que sa traduction dans la langue de Shakespeare et de Goethe !
```

### Message libre

```markdown
Ceci est un test, je vous laisse ou pas publier l'information... Qui commence à être un peu ancienne. Si ce type d'information vous intéresse, je ferai un envoi pour les nouvelles géomaticiennes dont les pages sont parues en français sur Wikipédia.
```

**Comment by Guts** [comment]
Ce dépôt est temporaire et va donc être supprimé sous peu.

Pouvez-vous réitérer cette news ou un autre sur https://github.com/geotribu/website/issues/new/choose ?

Merci bcp !
